### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by muvic08** [azawawi/SwiftyZeroMQ#10]
I have a long running background process and I am running socket.recv() on a loop. The memory use is building up indefinitely and I get the attached memory leak report. From zeromq docs, they recommend calling zmq_msg_close after zmq_recv. Any ideas? 

![screen shot 2017-01-11 at 3 29 21 pm](https://cloud.githubusercontent.com/assets/2608188/21865250/6612d966-d813-11e6-828d-7102eeb6247c.png)

**Comment by azawawi** [comment]
@muvic08  Could you provide the code that causes the memory leak?

**Comment by muvic08** [comment]
```swift 

// init 
do {
     self.context = try SwiftyZeroMQ.Context()
     self.subscriber = try context.socket(.subscribe)
     try subscriber.connect(self.endpoint)
     try self.subscriber.setSubscribe("publishedKey") // I pulled down version 1.0.24 
}
catch {}

public func listenForPublishedMessages(closurecb: @escaping (_ data: Any?, _ error: String?) -> Void) {
        if self.isSubscriberRunning { return }
        DispatchQueue.global(qos: .background).async {
            self.isSubscriberRunning = true
            var msg: String! = ""
            do {
                while true  {
                    msg = try self.subscriber.recv(bufferLength: 1000)
                    closurecb(data, nil)
                }
            } catch {}
        }
    }
```

I increased recv bufferLength because my payload was bigger than 250. 

The publisher I have is publishing a few times a second.

**Comment by azawawi** [comment]
Thanks for sharing your code. Please try if the following fixes your memory leak problem https://github.com/azawawi/SwiftyZeroMQ/commit/216677cb54add83bd775c87652d04bff72103ac2.

**Comment by muvic08** [comment]
Thank you very much. That fix worked!

**Comment by muvic08** [comment]
Unfortunately, the issue was not completely resolved. I still get the `zmq::shared_message_memory_allocator::allocate()` memory leak.

**Comment by azawawi** [comment]
Cool, we are getting there. Please share all the relevant ZeroMQ code and I will hopefully help 👍

**Comment by muvic08** [comment]
Hi, I made a few changes; added a poller. The thing that seems to work (am still running tests) is adding **autoreleasepool** inside the while loop. I will share conclusive results of my experiment later.

``` swift
// init 
do {
     self.context = try SwiftyZeroMQ.Context()
     self.subscriber = try context.socket(.subscribe)
     try subscriber.connect(self.endpoint)
     try self.subscriber.setSubscribe("publishedKey") // I pulled down version 1.0.24 
     self.poller = SwiftyZeroMQ.Poller()
     try poller.register(socket: self.subscriber,  flags: .pollIn)
}
catch {}

public func listenForPublishedMessages(closurecb: @escaping (_ data: Any?, _ error: String?) -> Void) {
        DispatchQueue.global(qos: .background).async {
            var msg: String! = ""
            do {
                while true  {
                     try autoreleasepool { // THIS SEEMS TO WORK!
                           var socks = try self.poller.poll(timeout: 1000)
                           if socks[self.subscriber] == SwiftyZeroMQ.PollFlags.pollIn {
                              msg = try self.subscriber.recv(bufferLength: 1000)
                              closurecb(data, nil)
                         }
                     }
                }
            } catch {}
        }
    }
```

**Comment by muvic08** [comment]
That worked very well. The memory is holding constant: 
<img width="415" alt="screen shot 2017-01-13 at 7 40 47 am" src="https://cloud.githubusercontent.com/assets/2608188/21930360/b3816ec8-d963-11e6-8cb0-6fc46adf2a06.png">

There is still a few leaks though. I think we need to tell zeromq to close the message but I don't know how to do that from swift.

<img width="1017" alt="screen shot 2017-01-13 at 7 37 58 am" src="https://cloud.githubusercontent.com/assets/2608188/21930393/d763a3b0-d963-11e6-9476-24eab75e4581.png">

**Comment by azawawi** [comment]
Great!

I am not sure we're even using `msg_t` directly. Please take a look at https://github.com/azawawi/SwiftyZeroMQ/blob/master/Sources/Socket.swift#L105 and https://github.com/azawawi/SwiftyZeroMQ/blob/master/Sources/Socket.swift#L119. I will take a look at it on Sunday given that I do not have a macOS development environment at the moment. How many times is `listenForPublishedMessages` called and how many times `.send` is called vs `.recv` with the 1000 bytes UTF-8 string payload? Do they match?

Please also remember that `.connect` is not blocking. ZeroMQ will connect later lazily. One more thing, I would add a little `usleep` in the `while true` loop to prevent 100% CPU usage.

**Comment by muvic08** [comment]
Right now, ```listenForPublishedMessages``` is called only once. ```.recv``` in the code above is listening to a ```.send``` server that is publishing ```~4 times``` a second. I don't have control of the ```.send``` payload (it varies) and I set ```bufferLength: 100000``` because of that dynamic ```.send``` size.

**Comment by azawawi** [comment]
@muvic08 Is it working now or still leaking?

**Comment by muvic08** [comment]
It is working fine those far!

**Comment by azawawi** [comment]
@muvic08 Cool 👍
