### ISSUE TITLE
Is the Subscribe implementation ready?

### ISSUE THREAD

**Issue by jamessugrue** [azawawi/SwiftyZeroMQ#11]
Hi @azawawi 
I just started using the latest from master so that I could try out a subscribe use case. It's great being able to pass through the extra socket options. 
I'm just wondering if it's too early, or should I expect it to work as it is?
Happy to help out!
James

**Comment by azawawi** [comment]
@jamessugrue Low level API is already available in case high level API does not work as expected. It should work. Please take a look at issue #10.  Contributions are more than welcome 👍 The socket setter and getter options do not cover all the ZeroMQ options at the moment (I think until 2.1 but certainly not 4.2).

**Comment by jamessugrue** [comment]
Thanks @azawawi .. I'm just about to give it a proper go now.

**Comment by azawawi** [comment]
@jamessugrue Have fun. Also take a look at the [ZeroMQ guide examples](https://github.com/booksbyus/zguide/tree/master/examples) for usage. I would look at the C (low-level) and python (high-level) examples. The [ZeroMQ guide](http://zguide.zeromq.org/page:all) is the definitive reference.

Closing 👍

**Comment by jamessugrue** [comment]
Works really well! Thank you. One question though, when do you plan on releasing 1.0.24? Just using master at the moment

Thanks 
James

**Comment by azawawi** [comment]
Thanks. I was hoping to write a simple publisher/subscriber example in the `README` and then publish it. 

The short answer working on it right now 👍

**Comment by jamessugrue** [comment]
Great! Let me know if I can help at all

**Comment by azawawi** [comment]
Added the example https://github.com/azawawi/SwiftyZeroMQ/commit/cb426a010c28367ba3814d6f7c26786ce5914f45. Please check it out. Your feedback is appreciated.

Hopefully tomorrow I will release `1.0.24`.

**Comment by azawawi** [comment]
`1.0.24` is out. Have fun.  👍 

Closing this issue.
