### ISSUE TITLE
Crash on iOS9

### ISSUE THREAD

**Issue by floriangbh** [azawawi/SwiftyZeroMQ#14]
Hello and thank you for this library !

I'm trying to implement zeroMQ with this lib but something seem to not work with iOS9 on my iPod touch.

```swift
do {
            // Define a TCP endpoint along with the text that we are going to send/recv
            let endpoint     = "tcp://<my_ip>"
            let textToBeSent = "{\"type\":\"connect\",\"apiToken\":\"<token>\"}"
            
            // Request socket
            let context      = try SwiftyZeroMQ.Context()
            let requestor    = try context.socket(.request) // THIS LINE CRASH
            try requestor.connect(endpoint)
            
            // Send it without waiting and check the reply on other socket
            try requestor.send(string: textToBeSent, options: .dontWait)
            let reply = try requestor.recv()
            print(reply)
        } catch {
            print(error)
        }
```

With this code, all work on iOS10 (with real device and simulator) and on iOS9 on simulator. But on my real device on iOS9 (iPod Touch 9.3.5) I have crash at this line : 
`let requestor    = try context.socket(.request) // THIS LINE CRASH`

There is any issue with iOS9 ? 
I don't have any other real device for trying it ...

Thank you

**Comment by jamessugrue** [comment]
It might be related to #13

**Comment by floriangbh** [comment]
Oops ! I had not read the whole issue... Thank you!

**Comment by azawawi** [comment]
No problem. It is definitely related to #13 as @jamessugrue said. I am working on it with the libzmq team (https://github.com/zeromq/libzmq/issues/2323). 

Apple's [addition of `clock_gettime` in macOS 10.12](https://google.com/#q=clock_gettime+macos+10.12) actually broke a lot of packages. So we are not alone after all :)

On a side note, I hate 13 as a number :)

I am closing this one. Thanks for reporting it.

**Comment by azawawi** [comment]
@terflogag Please try db00516. Sorry for the delay.

**Comment by floriangbh** [comment]
Hello @azawawi !

Just tried with your last commit https://github.com/azawawi/SwiftyZeroMQ/commit/db0051659a44db7f56c46b7755af32d4a2b8fce0 and I did not crash. But I can not really test with our server until Monday. But the issue seems to be fixed! 

Thank you a lot for your quickly fix 🥇

**Comment by azawawi** [comment]
@terflogag Perfect and thanks. I am going to patch 4.2.1 and submit patch to `libzmq` project. Looking forward for further test results.
