### ISSUE TITLE
Buffer lenght given for "recv" causes error

### ISSUE THREAD

**Issue by yilmazgamze** [azawawi/SwiftyZeroMQ#17]
In Socket.swift file, the recv function has bufferLength paramter given as constant 256. When the incoming message/reply exceeds this size, received string becomes nil. Thus the size needs to be larger but not definite. 
Maybe receiving might be reorganised or buffer and its size can be updated. I cound not decide which one would be better and I don't know exactly the process details. 

I only changed the size (256 to larger value) and problems solved because bufferSize was larger than bufferLength, it was obvious. But this is not a permanent solution.

**Comment by azawawi** [comment]
@gamzeylmz `bufferLength` is an optional parameter that you can override. Please let me know what you need.
