### ISSUE TITLE
Pub/Sub issue when running on iOS hardware.

### ISSUE THREAD

**Issue by bedford10** [azawawi/SwiftyZeroMQ#19]
I've been trying out a new application on using an ipad as a wired zeromq messaging server, and I've been having some issues getting it to work properly when running on the actual hardware. It works completely fine in the simulator.

* iOS hardware: has both a pub and a sub. Both the pub and the sub are bound.
* Python client 1: has both a pub and a sub that connect to the iOS hardware.
* Python client 2: same situation, running exact the same code.
* Both clients share the same subscription.

If client 1 connects first, everything works fine. When client 2 connects, the iOS hardware never sends a message to client 2 after the initial behind the scenes connection messages. However, it sends the message to client 1 since they share the same subscription.

Using wireshark, I was able to confirm that client 2 never received the messages. Using it further, I was able to get the iOS hardware recognized as a network interface and run tcpdump to examine what's happening on the iOS hardware side of things.

The iOS hardware is never sending to client 2. Even if connection order happens in reverse and client 1 connects second, the exact same symptoms happen to client 1. It just won't send a message.

Looking at your code, it appears that sending a message is just wrapped into a data format and sent down to the attached zeromq binary. I'm wondering if how the binary is handling these sockets for the hardware architecture/software environment isn't correct to how pub/sub should work. It's either that, or iOS/hardware is limiting me from sending to the second client entirely.

In order to make sure I was setting up the architecture correctly, I set up the exact same situation using pyzmq. Pyzmq seems to work perfectly fine.

I was wondering if you had any insight into this.

**Comment by azawawi** [comment]
@bedford10 Sorry the late reply on this one. Could please share the python server code so I can better help you out?
